### ISSUE TITLE
Support meta plugins

### ISSUE THREAD

**Issue by turb** [maestrodev/puppet-sonarqube#19]
Some plugins (e.g. csharp-plugin, php-plugin) are meta plugin with dependencies to maven submodules.

Hence, there is no http://repo1.maven.apache.org/maven2/org/codehaus/sonar-plugins/php/parent/2.4/parent-2.4.jar - only a parent pom.

It would be nice if puppet-sonarqube would be able to install such meta plugin.

Thanks!

**Comment by racodond** [comment]
Hi,

You can install such plugins by overriding the groupid parameter.
Here's how to install the latest version of the PHP plugin for example:
```
  sonarqube::plugin { 'sonar-php-plugin' :
    groupid => 'org.codehaus.sonar-plugins.php',
    version => '2.4.1',
  }
```

Regards,
