### ISSUE TITLE
Puppet tries to download the SonarQube plugins with Maven before having installed Maven

### ISSUE THREAD

**Issue by racodond** [maestrodev/puppet-sonarqube#22]
Hi,

The following piece of code works to install SonarQube. Maven is not required unlike what it is stated in the README file.
```
class { 'java': }
class { 'sonarqube' :
  version => '3.7.4',
}
```

Maven is only necessary when some SonarQube plugins need to be downloaded and installed. But in this case, you cannot add ```class { 'maven::maven' : } ->``` because it is duplicated by https://github.com/maestrodev/puppet-sonarqube/blob/master/manifests/plugin.pp#L32 and thus an error is thrown.

To install a plugin, the following piece of code does not work as well:
```
class { 'java': }
class { 'sonarqube' :
  version => '3.7.4',
}
sonarqube::plugin { 'sonar-build-breaker-plugin' :
  version => '1.1',
  notify  => Service['sonar'],
}
```
I am not an expert in Puppet dependencies, but https://github.com/maestrodev/puppet-sonarqube/blob/master/manifests/plugin.pp#L32 does not seem to guarantee that Maven is installed prior to downloading the plugins with Maven. During my tests, Puppet always tries to download the plugins before having installed Maven. Thus I need to run ```vagrant up``` + ```vagrant provision``` to get something up and running.

What is working for me is:
1. Remove https://github.com/maestrodev/puppet-sonarqube/blob/master/manifests/plugin.pp#L32
2. Execute the following piece of code (with ```class { 'maven::maven': } ->```):
```
class { 'java': }
class { 'maven::maven': }
->
class { 'sonarqube' :
  version => '3.7.4',
}
sonarqube::plugin { 'sonar-build-breaker-plugin' :
  version => '1.1',
  notify  => Service['sonar'],
}
```

Should I submit a PR removing https://github.com/maestrodev/puppet-sonarqube/blob/master/manifests/plugin.pp#L32 and updating the README file?

Thank you

Regards,

David RACODON

**Comment by carlossg** [comment]
Yes, please a PR would be fine. I don't think this module should install maven, just add it to the readme as a pre-requisite

**Comment by racodond** [comment]
PR created: https://github.com/maestrodev/puppet-sonarqube/pull/26
