### ISSUE TITLE
Typo in the description of the repository

### ISSUE THREAD

**Issue by racodond** [maestrodev/puppet-sonarqube#38]
@carlossg: There's a typo in the description of the repository at https://github.com/maestrodev/puppet-sonarqube: Puppet module for Sonaqube => Puppet module for SonarQube. Could you please fix it because I don't have enough rights?

Also, for your information, I made the module be referenced on http://docs.sonarqube.org/display/PLUG/Community+Plugins#CommunityPlugins-Othercontributions

**Comment by carlossg** [comment]
fixed
