### ISSUE TITLE
Unable to start sonar service

### ISSUE THREAD

**Issue by digitalbear** [maestrodev/puppet-sonarqube#43]
Hi,

I was getting the following issue with the sonar service after installation:
```
$ sudo systemctl status sonar
sonar.service - LSB: Sonar
   Loaded: loaded (/etc/rc.d/init.d/sonar)
   Active: failed (Result: exit-code) since Fri 2015-08-21 16:22:04 UTC; 3min 5s ago
  Process: 554 ExecStart=/etc/rc.d/init.d/sonar start (code=exited, status=203/EXEC)

Aug 21 16:22:04 sonarqube systemd[1]: sonar.service: control process exited, code=exited status=203
Aug 21 16:22:04 sonarqube systemd[1]: Failed to start LSB: Sonar.
Aug 21 16:22:04 sonarqube systemd[1]: Unit sonar.service entered failed state.
```

My set-up:
Windows 7 host, running puppetlabs/centos-7.0-64-puppet box on Vagrant, using Puppet-SonarQube 2.6.2

I eventually figured out that the problem is that the installed sonar.sh file has carriage return characters  (DOS line endings) and so cannot be executed.  I have resolved manually with the following:
$ cd /usr/local/sonarqube-5.1.2/bin/linux-x86-64
$ sudo cp sonar.sh sonar.sh.original
$ sudo sh -c "tr -d '\r' < sonar.sh.original > sonar.sh"
$ sudo systemctl daemon-reload
$ sudo systemctl start sonar.service

But there should be some way to include this in the untar step or add a subsequent step, but I am new to Puppet so not quite sure how to do that at the moment.

Funny, I didn't have this issue when I did the same set-up from my Mac at home.

Thanks for looking into this.  Cheers

**Comment by racodond** [comment]
Hi @digitalbear,

I'm not sure to fully understand your issue.

> I eventually figured out that the problem is that the installed sonar.sh file has carriage return characters 

The `sonar.sh.erb` file does not seem to have carriage return characters: https://github.com/maestrodev/puppet-sonarqube/blob/master/templates/sonar.sh.erb

> But there should be some way to include this in the untar step or add a subsequent step, but I am new to Puppet so not quite sure how to do that at the moment.

The `sonar.sh` that is used is not the one provided with the downloaded SonarQube package. It is replaced with the `sonar.sh.erb` template provided with the SonarQube Puppet module: https://github.com/maestrodev/puppet-sonarqube/blob/master/manifests/init.pp#L137

> Funny, I didn't have this issue when I did the same set-up from my Mac at home.

My guess would be that the carriage return characters were added when you retrieved the SonarQube Puppet module from GitHub. How did you retrieve the module? Is line ending properly configured within your Git client: https://help.github.com/articles/dealing-with-line-endings/ ?

Cheers,

**Comment by digitalbear** [comment]
Hi @racodond 

My Git config appears to be correct, but I didn't use Git to download the SonarQube package, I just downloaded it with my browser from the puppet forge website.  I then opened it up in WinZip and extracted it to my local drive where my Vagrantfile is located.  This is so that I can access the SonarQube package from within the Vagrant box, using Vagrant's "synched folders" functionality.

On further investigation it appears this is an issue with using Vagrant on a windows host in this particular way - see http://blog.xjtian.com/post/54399466362/vagrant-tips-for-windows-users.  

And nothing to do with the SonarQube package.  Sorry about that.

**Comment by racodond** [comment]
> On further investigation it appears this is an issue with using Vagrant on a windows host in this particular way - see http://blog.xjtian.com/post/54399466362/vagrant-tips-for-windows-users.

Thanks for the info.

> And nothing to do with the SonarQube package. Sorry about that.

No problem :-)
