### ISSUE TITLE
pushd not available to /bin/sh

### ISSUE THREAD

**Issue by chris-redekop** [maestrodev/puppet-sonarqube#46]
While running SonarQube with puppet-sonarqube, I hit the following error.  I think this is related to dd03c9ddae32403a14a235f11f612ce3dc6db8c0 , since pushd is a bash builtin and not available to /bin/sh.

==> default: Notice: /Stage[main]/Sonarqube/Service[sonarqube]/ensure: ensure changed 'stopped' to 'running'
==> default: Notice: /Stage[main]/Sonarqube/File[/tmp/cleanup-old-plugin-versions.sh]/ensure: defined content as '{md5}1ef30f89670a3449c01d6f63152fa2e9'
==> default: Notice: /Stage[main]/Sonarqube/File[/tmp/cleanup-old-sonarqube-versions.sh]/ensure: defined content as '{md5}4c2984d86a11984f6d348f2ed7986c1b'
==> default: Error: /tmp/cleanup-old-sonarqube-versions.sh: 3: /tmp/cleanup-old-sonarqube-versions.sh: pushd: not found
==> default: /tmp/cleanup-old-sonarqube-versions.sh: 11: /tmp/cleanup-old-sonarqube-versions.sh: popd: not found
==> default: Error: /Stage[main]/Sonarqube/Exec[remove-old-versions-of-sonarqube]/returns: change from notrun to 0 failed: /tmp/cleanup-old-sonarqube-versions.sh: 3: /tmp/cleanup-old-sonarqube-versions.sh: pushd: not found
==> default: /tmp/cleanup-old-sonarqube-versions.sh: 11: /tmp/cleanup-old-sonarqube-versions.sh: popd: not found
==> default: Notice: Finished catalog run in 133.78 seconds

**Comment by racodond** [comment]
@chris-redekop You're right. I'll revert this commit.
