### ISSUE TITLE
Releasing 2.6.4 on puppet forge

### ISSUE THREAD

**Issue by PierreR** [maestrodev/puppet-sonarqube#47]
I would love a  `2.6.4` release ;-)

Thanks

**Comment by racodond** [comment]
Released: https://github.com/maestrodev/puppet-sonarqube/releases/tag/v2.6.4

**Comment by PierreR** [comment]
I meant on puppet forge, sorry. 

It is just easier to upgrade when it is there but I can easily do that using git instead.

**Comment by PierreR** [comment]
Thanks I can see it is there now.
