### ISSUE TITLE
sonar-runner's sonarqube_server paramenter does not populate template properly

### ISSUE THREAD

**Issue by velocity303** [maestrodev/puppet-sonarqube#49]
$sonarqube_server parameter should be included in the sonarqube::runner::config class so that the parameter passes properly to the template.

**Comment by andreyev** [comment]
Looks fine here! Could you, please, release it?

TIA!
--
Andreyev

**Comment by racodond** [comment]
Released: https://github.com/maestrodev/puppet-sonarqube/releases/tag/v2.6.5
