### ISSUE TITLE
Installation for Sonarqube 5.2 not possible, wrong URL

### ISSUE THREAD

**Issue by Robbe64** [maestrodev/puppet-sonarqube#51]
The installation of sonar 5.2 is not possibel because the requested URL (http://downloads.sonarsource.com/sonarqube/sonarqube-5.2.zip) does not exist.

By the way, do I have to do anything special to migrate from 4.5.x to 5.x ?

**Comment by racodond** [comment]
Thanks for the feedback. See https://github.com/maestrodev/puppet-sonarqube/pull/53/files
