### ISSUE TITLE
Cannot download SonarQube 5.2

### ISSUE THREAD

**Issue by Cosaquee** [maestrodev/puppet-sonarqube#65]
```
Notice: /Stage[main]/Sonarqube/Wget::Fetch[download-sonar]/Exec[wget-download-sonar]/returns: http://downloads.sonarsource.com/sonarqube/sonarqube-5.2.zip:
Notice: /Stage[main]/Sonarqube/Wget::Fetch[download-sonar]/Exec[wget-download-sonar]/returns: 2016-03-02 05:29:59 ERROR 404: Not Found.
Error: wget --no-verbose --output-document="/usr/local/src/sonarqube-5.2.zip" "http://downloads.sonarsource.com/sonarqube/sonarqube-5.2.zip" returned 8 instead of one of [0]
Error: /Stage[main]/Sonarqube/Wget::Fetch[download-sonar]/Exec[wget-download-sonar]/returns: change from notrun to 0 failed: wget --no-verbose --output-document="/usr/local/src/sonarqube-5.2.zip" "http://downloads.sonarsource.com/sonarqube/sonarqube-5.2.zip" returned 8 instead of one of [0]
```

This is caused by lack of SonarQube 5.2 in their repo. Last version of SonarQube available is: 5.1.

Would be nice to have any info about that. I can submit PR with change in README.md if you do not have time. 

KK

**Comment by racodond** [comment]
Thanks for the feedback. All the binaries have been moved to https://sonarsource.bintray.com/Distribution/sonarqube/
If you want to provide a PR to update the source code, you're more than welcome!

**Comment by Cosaquee** [comment]
I will submit the PR : )

Would be nice to have some informations about how to contribute to this project. I will try to add informations about tests, how to run them and some basic guidelines for next contributors(CONTRIBUTING.md) if this is ok for you ?

**Comment by Cosaquee** [comment]
Ok, we have this problem with lack of version 5.2 because in your last released version there is still old link(http://downloads.sonarsource.com/sonarqube/sonarqube-5.2.zip). Fix for that is in commit b5d9c6acf4adec33943110c79c3827b4ce8258fc. Do you have any road plan that will show when will be next release with that fix ?

**Comment by racodond** [comment]
Completely forgot that this issue was already fixed. I just released a new version including this fix: https://github.com/maestrodev/puppet-sonarqube/releases/tag/v2.6.7
It should be available soon at https://forge.puppetlabs.com/maestrodev/sonarqube

**Comment by racodond** [comment]
I'll close this PR and have a look at your "contributing" PR.
